FROM postgres:15.3-alpine3.18
# link to image: https://hub.docker.com/_/postgres/

ARG username="root"
ARG password="password"
ARG db="pwpc"

ENV POSTGRES_PASSWORD=${password}
ENV POSTGRES_USER=${username}
ENV POSTGRES_DB=${db}

COPY ./.docker/postgres/. docker-entrypoint-initdb.d